### ISSUE TITLE
Unexpectedly losing work after it appears to be correctly saved

### ISSUE THREAD

**Issue by jasonrohrer** [flathub/org.gnumeric.Gnumeric#10]
My wife has PopOS on her laptop.  She needed a spreadsheet, so we searched for Gnumeric in the PopShop.  For whatever reason, the FlatPak version came up first, and I installed that without giving it much thought.

Then I set about helping her create a spreadsheet for her project, writing a bunch of macros, and having her enter some of the data.  We saved it, quit Gnumeric, and then I was going to show her how to find the file tomorrow to work on it again.  And the file was gone.  WTF?

So I thought I made a mistake... maybe I hit Cancel instead of Save?

So then I re-created the spreadsheet AGAIN, and this time, I made sure it was saved.  I closed it in Gnumeric and re-opened it.  YES, it worked this time!

But then today, we went to look for it in Gnumeric, and it's gone again.

Worse, it was apparently not saved anywhere.  Not in some temp directory.

So we have lost our work TWICE at this point.  Of course, I'm going to uninstall the FlatPak version now, and install the regular apt install one.

But for a program like Gnumeric, or Gimp, or Libre Office....  FlatPak seems totally useless, at least in the default configuration.  Who would ever want to use these programs and NOT save their work?

Since the normal way of using an Office program is to save your work.... any FlatPak version of such programs should warn the user repeatedly that files aren't really saved.  That this is a temporary session, etc.

I understand how FlatPak could be useful for a web browser or something else that doesn't save files.

But for software that usually saves files---and in the case of FlatPak, appears to save files but lies about it---the situation is ridiculous.

Looking at her system now, I see a bunch of things that were installed by PopShop as flatpaks.  GIMP is another example.  She used that to edit pictures last month, and guess what?  All that work is lost too!  She didn't even realize this was possible, and had no idea the files were lost until I just checked.

Since PopOS is supposed to be user-friendly for non-technical users (like my wife), the Flatpaks should be REMOVED from PopShop, if there's another option available.

This is a terrible trap for a new user---these applications appear to save your work, but don't actually save it, and there's no warning of any kind, not even on the PopShop listing for the app ("WARNING--THIS IS A FLATPAK---YOUR WORK WILL NOT BE SAVED IF YOU USE THIS")

This was a terrible trap for ME, an engineer with 25+ years of experience as a systems programmer and a linux user.  I lost my work twice with no warning.

And my wife now feels like she can't trust her PopOS Laptop, and wants to get rid of it...

**Steps to reproduce (if you know):**

Install Gnumeric with PopShop (flatpak version)

Open it and create a spreasheet.  Save it in the Documents folder.

Inside Gnumeric, go to Open, and verify that the file was saved correctly.

Quit Gnumeric.

Open Gnumeric again and try to find the file that you saved before.  It's gone.

**Expected behavior:**

Saved files should really be saved and available next time you run the app.

OR

A very obvious warning should be displayed whenever you run a flatpak app.

**Comment by jasonrohrer** [comment]
Was originally posted here:

https://github.com/pop-os/pop/issues/2877

I actually think this is a PopOS issue, and PopOS should stop recommending Flatpaks in their PopShop for things like Gnumeric and GIMP.

But the PopOS people tell me that maybe there's something in the flatpak's config that could be fixed here?

**Comment by TingPing** [comment]
Just to document the problem.

Gnumeric either should:

- Have broader permissions, be it `filesystem` or `persist`
- Use the proper file chooser portal (ideal of course)

This is not a problem with any of the other packages mentioned.

**Comment by hfiguiere** [comment]
> Have broader permissions, be it filesystem or persist

pr #13
