### ISSUE TITLE
default to use the filechooser portal

### ISSUE THREAD

**Issue by firefoxlover** [flathub/org.gnumeric.Gnumeric#15]
https://gitlab.gnome.org/GNOME/gnumeric/-/issues/760

For some reason gnumeric does not use the filechooser portal for me.

`GDK_DEBUG=portals` is a workaround that should not be used to my knowledge.

The static filesystem permissions are too strict, so it is pretty much unusable for me.

KDE Plasma 6 Wayland, portal is there.

**Comment by hfiguiere** [comment]
> For some reason gnumeric does not use the filechooser portal for me.

It's an upstream problem.

You can change the static permission in you setup.
